### ISSUE TITLE
Regarding training images resolution

### ISSUE THREAD

**Issue by malayjoshi13** [weecology/NeonTreeEvaluation_package#28]
Hi, I wanted to re-train the existing model used in this package. For that, I understood that training images must be RGB and of size 400*400. But I didn't understand how to determine spatial resolution while capturing images from Google Earth. I read in the documentation that 0.1m spatial resolution is standard, so how will I know that image I am about to save from Google Earth is of 0.1m spatial resolution.

**Comment by bw4sz** [comment]
Sorry I missed this, this repo is for evaluation. If this is still a need post on the data repo https://github.com/weecology/NeonTreeEvaluation, or probably better yet deepforest.readthedocs.io
