### ISSUE TITLE
download function does not necessarily work "out of the box"

### ISSUE THREAD

**Issue by Lenostatos** [weecology/NeonTreeEvaluation_package#29]
Dear Mr. Weinstein,

when I tried to execute the code of the Data vignette, I got an error with the `download` function:

```
NeonTreeEvaluation::download()
Downloading file to /home/leon/Projects/RPackages/NeonTreeEvaluation_package/renv/library/R-4.0/x86_64-pc-linux-gnu/NeonTreeEvaluation/extdata/NeonTreeEvaluation.zip
trying URL 'https://zenodo.org/api/files/012fcb19-a0e0-4d08-9793-62ba35a4adb6/weecology/NeonTreeEvaluation-1.7.1.zip'
Content type 'application/octet-stream' length 1962013082 bytes (1871.1 MB)
==
downloaded 103.5 MB

Error in download.file(eval_url, destination, mode = "wb") : 
  download from 'https://zenodo.org/api/files/012fcb19-a0e0-4d08-9793-62ba35a4adb6/weecology/NeonTreeEvaluation-1.7.1.zip' failed
In addition: Warning messages:
1: In download.file(eval_url, destination, mode = "wb") :
  downloaded length 108485754 != reported length 1962013082
2: In download.file(eval_url, destination, mode = "wb") :
  URL 'https://zenodo.org/api/files/012fcb19-a0e0-4d08-9793-62ba35a4adb6/weecology/NeonTreeEvaluation-1.7.1.zip': Timeout of 60 seconds was reached
```

The timeout mentioned at the end of that error message is changeable via `options(timeout = x)` which was what I used to download the data in the end. To make the `download` function work "out of the box" the documentation of the `download.file` function (which is used internally by `download`) contains a suggestion:

> The timeout for many parts of the transfer can be set by the option timeout which defaults to 60 seconds. This is often insufficient for downloads of large files (50MB or more) and so should be increased when download.file is used in packages to do so. Note that the user can set the default timeout by the environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of R, so to ensure that this is not decreased packages should use something like
> ```
>     options(timeout = max(300, getOption("timeout")))
> ```
>   
> (It is unrealistic to require download times of less than 1s/MB.)

It's not mentioned there but I've read [here](https://r-pkgs.org/r.html?q=options#code-r-landscape) that it is bad practice to change the options of a user's R session. Maybe something like the following would be appropriate:

```r
timeout_option_backup <- getOption("timeout")
options(timeout = max(2000, getOption("timeout")))

# Call download.file() here

options(timeout = timeout_option_backup)
```

The 2000 is just a placeholder. It's probably better to determine the size of the to-be-downloaded file beforehand and use that for a more meaningful value.

**Comment by bw4sz** [comment]
Thanks @Lenostatos , keep it coming.

@henrykironde  do you have a suggestion here? What is the preferred way of changing to the download function. I'm guessing that this is dependent on the user's internet speed. I've never run into this issue. 

@juniperlsimonis I pulled some of this code from Portal a while ago, did you run into this?

https://github.com/weecology/NeonTreeEvaluation_package/blob/master/R/download.R

**Comment by juniperlsimonis** [comment]
yes, we hit this same issue as archives started to grow.

i'm working on a newer iteration right now, but my suggestion would be to bring the time up to an argument to avoid locking in the timeout backstop. so, building on @Lenostatos , something akin to 

```
fun <- function(max_time = 2000){

timeout_option_backup <- getOption("timeout")
options(timeout = max(max_time, getOption("timeout")))

# Call download.file() here

options(timeout = timeout_option_backup)


}
```
