### ISSUE TITLE
error with download() "[...]extdata/NeonTreeEvaluation.zip' cannot be opened"

### ISSUE THREAD

**Issue by Lenostatos** [weecology/NeonTreeEvaluation_package#33]
The `download()` function appears to be not working anymore for me:

``` r
NeonTreeEvaluation::download()
#> Downloading file to /[...]/renv/library/R-4.1/x86_64-pc-linux-gnu/NeonTreeEvaluation/extdata/NeonTreeEvaluation.zip
#> Warning in download.file(eval_url, destination, mode = "wb"): URL https://
#> zenodo.org/api/files/d5c9f957-f439-4088-bf58-23bf679575d9/weecology/
#> NeonTreeEvaluation-1.8.0.zip: cannot open destfile '/[...]/renv/library/R-4.1/x86_64-pc-
#> linux-gnu/NeonTreeEvaluation/extdata/NeonTreeEvaluation.zip', reason 'No such
#> file or directory'
#> Warning in download.file(eval_url, destination, mode = "wb"): download had
#> nonzero exit status
#> Error in unzip(destination, list = TRUE): zip file '/[...]/renv/library/R-4.1/x86_64-pc-linux-gnu/NeonTreeEvaluation/extdata/NeonTreeEvaluation.zip' cannot be opened
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I am suspecting that this is related to the `extdata` directory because I have observed on my machine that this directory is missing after a fresh install of the package. The directory might be missing because there are no longer any files in that directory since the last commit 36fb9ef5f0bc396835c2ba89b43b72d4d5159291. 

Do you also experience this issue? Maybe the extdata directory can be created manually in `download()`?

**Comment by bw4sz** [comment]
I added a .gitkeep to extdata folder to keep it around. Deleting and the data and redownloading worked fine for me.

c4d99533e5dfb80f9e0ec32e66623001ea139bbd

```
> library(NeonTreeEvaluation)
> download()
Downloading file to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/NeonTreeEvaluation/extdata/NeonTreeEvaluation.zip
trying URL 'https://zenodo.org/api/files/d5c9f957-f439-4088-bf58-23bf679575d9/weecology/NeonTreeEvaluation-1.8.0.zip'
Content type 'application/octet-stream' length 3872242990 bytes (3692.9 MB)
=
```

**Comment by Lenostatos** [comment]
:+1: It works for me now, too.
