### ISSUE TITLE
Why match ground truth and prediction based on overlap and not based on jaccard?

### ISSUE THREAD

**Issue by Lenostatos** [weecology/NeonTreeEvaluation_package#34]
Hi Ben,

as far as I understand the code of [`compute_precision_recall()`](https://github.com/weecology/NeonTreeEvaluation_package/blob/c4d99533e5dfb80f9e0ec32e66623001ea139bbd/R/compute_precision_recall.R) you match individual ground truth and prediction polygons by maximizing their overall overlap with [`clue::solve_LSAP()`](https://github.com/weecology/NeonTreeEvaluation_package/blob/c4d99533e5dfb80f9e0ec32e66623001ea139bbd/R/assign_trees.R). Then you calculate the Jaccard index of the matched polygons.

I was wondering why you don't match ground truth and predictions based on their jaccard index? This would probably not make much of a difference in most cases but I have encountered scenarios where it might matter. 
More specifically, I encountered cases of undersegmentation where adjacent trees were recognized as just one tree. When such trees stand in a somewhat diagonal line with regards to the xy-coordinate system of the bounding boxes, they will have one very large bbox. Small bboxes of individually detected trees next to such an undersegmentation might completely fall inside the large bbox. Now let's imagine there is a _ground truth_ bbox for such an individual tree next to an undersegmented cluster. The ground truth bbox might not perfectly overlap with the bbox of the segmented tree but it might overlap completely with the large bbox of the undersegmented cluster next to it. Now, matching segmentation and ground truth bboxes by maximizing their overlap area might lead to the ground truth bbox of our small tree being assigned to the larger bbox of the undersegmented cluster. A matching based on the overlap-over-union on the other hand would likely assign the ground truth bbox correctly or at least not to the large bbox.

I hope my description is understandable. If not, please let me know and I will provide a graphical illustration.

Cheers,
Leon

**Comment by Lenostatos** [comment]
@bw4sz
Hi Ben,

I trust you to have good reasons for doing the matching the way you do. I was just curious in those reasons.

Please allow me to try to explain my understanding of the matter once more so that it might become easier to explain where I'm wrong:

1. When evaluating the segmentation of a single plot/image one starts off with a set of rectangles for the segmented trees and another set of rectangles draped by hand.
2. Next, one tries to create a situation where each hand-draped rectangle is assigned a segmentation counterpart that overlays it as much as possible.
3. The handDrape-segmentation rectangle pairs can then be evaluated for their ratio of intersection over union (=Jaccard index).

Finding that handDrape-segmentation pairing in step 2 is where I would have decided for a slightly different strategy. Currently the pairs are found by first calculating the overlap of each possible handDrape-segmentation pair and then finding an overall matching situation where that overlap is maximized.

To me, it seems more meaningful to calculate and maximize the Jaccard index instead of the overlap because of the case described in my initial post.

What's you opinion on this?

Cheers,
Leon

**Comment by ethanwhite** [comment]
@Lenostatos - just a heads up that @bw4sz is off this week so won't be around to respond to this for a while.
