### ISSUE TITLE
`download` function not currently working

### ISSUE THREAD

**Issue by georgewoolsey** [weecology/NeonTreeEvaluation_package#36]
I get the error `Error in vers[i] <- cont[[i]]$metadata$version : replacement has length zero` when running `NeonTreeEvaluation::download(training = F, force = F)` 

I am using NeonTreeEvaluation_0.1.0 in R version 4.3.0 running under Windows 10 x64 (build 19045)

I traced the error to line 44 `eval_url<-zenodo_url(concept_rec_id=3723356)` of [download.R](https://github.com/weecology/NeonTreeEvaluation_package/blob/c4d99533e5dfb80f9e0ec32e66623001ea139bbd/R/download.R)

I was able to successfully use `download()` after redefining the `zenodo_versions` and  `zenodo_url` functions in [zenodo_url.R](https://github.com/weecology/NeonTreeEvaluation_package/blob/c4d99533e5dfb80f9e0ec32e66623001ea139bbd/R/zenodo_url.R) using the code below (note the `tidyverse` ;) )

```
library(tidyverse)
zenodo_versions <- function(concept_rec_id, arg_checks = TRUE){
  url <- paste0("https://zenodo.org/api/records/?size=9999&",
                "q=conceptrecid:", concept_rec_id, "&all_versions=True")
  res <- httr::GET(url)
  httr::stop_for_status(res)
  cont <- httr::content(res)
  nv <- length(cont)
  
  # set up blank tibble for filling
  df <- dplyr::tibble(
    version = character(0)
    , rec_id = character(0)
  ) 
  
  # loop over nv and fill df
  for(i in 1:nv){
    # convert messy list to tibble
    cont_df <- cont[[1]]$hits %>% 
      unlist() %>% # collapse messy list
      stack() %>% # convert to data frame
      dplyr::as_tibble() %>% # convert to tibble
      dplyr::group_by(ind) %>% # get list order by name of parameter
      dplyr::mutate(n = dplyr::row_number())
    
    # get the columns needed... NOTE THE CHANGES
      # record_id ... now known as recid
      # metadata$version ... now known as metadata.version
    cont_df <- cont_df %>% 
      dplyr::filter(ind %in% c("recid", "metadata.version")) %>% # keep only the record and version
      tidyr::pivot_wider(names_from = ind, values_from = values) %>% # pivot wider
      dplyr::rename(version = metadata.version, rec_id = recid) %>% # rename
      dplyr::select(version, rec_id, n)
    
    # bind the rows
    if(nrow(cont_df)>0){
      df <- dplyr::bind_rows(df, cont_df)
    }
  }
  # return it dropping duplicates
  return( dplyr::distinct(df) )
}
# test it
zenodo_versions(concept_rec_id = 3723356)
    
# Obtain the URL for a Zenodo record to be downloaded
zenodo_url <- function(concept_rec_id = 3723356, rec_version = "latest",rec_id = NULL){

  if(is.null(rec_id)){
    avail_versions <- zenodo_versions(concept_rec_id = concept_rec_id)
    if(rec_version == "latest"){
      # rec_id <- concept_rec_id # original
      rec_id <- avail_versions %>% dplyr::filter(n==1) %>% dplyr::pull(rec_id)
    } else{
      spot <- which(avail_versions$version == rec_version)
      if(length(spot) == 0){
        stop(paste0("version ", rec_version, " not available"), call. = FALSE)
      }
      rec_id <- avail_versions$rec_id[spot]
    }
  } else if (!is.null(concept_rec_id)){
    warning("both concept_rec_id and rec_id input. rec_id takes precedence")
  }
      
  url <- paste0("https://zenodo.org/api/records/", rec_id)
  res <- httr::GET(url)
  httr::stop_for_status(res)
  # httr::content(res)$files[[1]]$links$download # original
  httr::content(res)$files[[1]]$links[[1]]
}

# test it
zenodo_url()
```

**Comment by ethanwhite** [comment]
Thanks for reporting this @georgewoolsey! I can replicate this bug. Looks like it's due to an API change at Zenodo. Since you've already got a fix implemented would you be up for submitting it as a PR?

**Comment by georgewoolsey** [comment]
I attempted to push a branch with the fix but don't have access to contribute as I got the following attempting `git push`:

` Permission to weecology/NeonTreeEvaluation_package.git denied to georgewoolsey.`

**Comment by ethanwhite** [comment]
Thanks @georgewoolsey. The standard way to do this is to create a fork of the repository by clicking on the Fork button in the top right corner of the main page:

![image](https://github.com/user-attachments/assets/1ae7064c-ffac-45cf-9628-e8cf4ff9d378)

This will create a copy of the repo in your GitHub account (at https://github.com/georgewoolsey/NeonTreeEvaluation_package/), which you can push your branch to. The easiest way to do this is to go into your current local repo and add your new repo as a new remote (sorry if I'm saying stuff you're already familiar with):

```
git remote add YourForkName https://github.com/georgewoolsey/NeonTreeEvaluation_package.git
git push YourBranchName YourForkName
```

`YourForkName` can be anything you want.

Once you've done that, on the main page of this repo you should see a banner asking if you want to open a pull request.

Let me know if you have any questions or if this is all too much of a pain and you'd prefer us to make the changes on our end.

**Comment by georgewoolsey** [comment]
> Thanks @georgewoolsey. The standard way to do this is to create a fork of the repository by clicking on the Fork button in the top right corner of the main page:

I initially forgot my 🍴 but got it now. Thanks for the reminder!
